### ISSUE TITLE
WSOD in wp-admin after AdminColumns udpdate

### ISSUE THREAD

**Issue by neilgilmour** [JoryHogeveen/ac-addon-members#1]
## Expected Behavior
access to wp-admin

## Actual Behavior
WSOD just in wp-admin after updating AC to v4.3.4

debug.log gives this:
```
[28-Jun-2018 08:27:11 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method AC\AdminColumns::autoloader() in /www/xxxx/public/wp-content/plugins/ac-addon-members/ac-addon-members.php:59
Stack trace:
#0 /www/xxxx/public/wp-includes/class-wp-hook.php(286): ACA_Members->init('')
#1 /www/xxxx/public/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /www/xxxx/public/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /www/xxxx/public/wp-settings.php(434): do_action('after_setup_the...')
#4 /www/xxxx/public/wp-config.php(94): require_once('/www/xxxx...')
#5 /www/xxxx/public/wp-load.php(37): require_once('/www/xxxx...')
#6 /www/xxxx/public/wp-admin/admin.php(31): require_once('/www/xxxx...')
#7 /www/xxxx/public/wp-admin/index.php(10): require_once('/www/xxxx...')
#8 {main}
  thrown in /www/xxxx/public/wp-content/plugins/ac-addon-members/ac-addon-members.php on line 59
```

## Steps to Reproduce the Problem

  1. update AC to v4.3.4
  1. go to wp-admin
  1.

## Specifications

  - Plugin Version: 1.0
  - WordPress Version: 4.9.6
  - Other plugins installed: lots
  - Theme: custom
  - Browser: Chrome

**Comment by DGStefan** [comment]
@neilgilmour
I'm a developer of Admin Columns and have access to this repo.
I just fixed this issue in a different branch:
https://github.com/JoryHogeveen/ac-addon-members/tree/1-admin-columns-update

@JoryHogeveen Can you do the merge, checks and release. We did not yet updated Admin Columns (free) so this version now only works with the new namespaces in ACP 4.3.

The release of Admin Columns free is planned for this week.
